version: "3.9"
services:
  rustpython:
    build: .
    container_name: rustpython_dev
    volumes:
      - .:/usr/src/app   # tu c√≥digo local se monta en el contenedor
    ports:
      - "8888:8888"      # para acceder a Jupyter Notebook desde el host
    tty: true            # mantiene la terminal abierta
