version: "3.9"
services:
  rustpython:
    build: .
    container_name: rustpython_dev
    volumes:
      - .:/usr/src/app   # tu c√≥digo local se monta en el contenedor
    tty: true            # mantiene la terminal abierta
